import { Expert, Consultation, Message, Conversation, Report, Review, SubscriptionPlan, DashboardStats, User } from '../types';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Karim Benali',
  email: 'karim.benali@example.com',
  role: 'client',
  company: 'TechStart DZ',
  position: 'CEO',
  subscription: 'professional',
  createdAt: '2024-01-15',
};

export const MOCK_EXPERTS: Expert[] = [
  {
    id: 'e1',
    name: 'Sarah Mansouri',
    avatar: 'https://i.pravatar.cc/150?img=1',
    title: 'Strategy Consultant',
    company: 'McKinsey Alumni',
    rating: 4.9,
    reviewCount: 128,
    consultations: 500,
    yearsExperience: 12,
    expertise: ['Market Entry', 'Business Strategy', 'Growth', 'M&A'],
    industries: ['Finance', 'Tech', 'Retail'],
    languages: ['Arabic', 'French', 'English'],
    bio: 'Strategic advisor specializing in the North African market with 12+ years experience helping companies expand into the Algerian and MENA markets.',
    hourlyRate: 150,
    currency: 'USD',
    availability: 'Available Today',
    category: 'Strategy',
    isVerified: true,
    isOnline: true,
    responseTime: '< 1 hour',
    location: 'Algiers, Algeria',
  },
  {
    id: 'e2',
    name: 'Youssef Rahmani',
    avatar: 'https://i.pravatar.cc/150?img=3',
    title: 'Financial Advisor',
    company: 'BNP Paribas Alumni',
    rating: 4.8,
    reviewCount: 94,
    consultations: 320,
    yearsExperience: 10,
    expertise: ['Investment', 'Corporate Finance', 'Risk Management', 'Valuation'],
    industries: ['Banking', 'Insurance', 'Real Estate'],
    languages: ['Arabic', 'French'],
    bio: 'Specialized in corporate finance, investment strategy, and financial risk management for Algerian and North African businesses.',
    hourlyRate: 120,
    currency: 'USD',
    availability: 'Available Tomorrow',
    category: 'Finance',
    isVerified: true,
    isOnline: false,
    responseTime: '< 2 hours',
    location: 'Oran, Algeria',
  },
  {
    id: 'e3',
    name: 'Amina Khelil',
    avatar: 'https://i.pravatar.cc/150?img=5',
    title: 'Legal Expert',
    company: 'Cabinet Khelil & Associés',
    rating: 4.7,
    reviewCount: 76,
    consultations: 210,
    yearsExperience: 8,
    expertise: ['Corporate Law', 'Contract Drafting', 'Compliance', 'IP'],
    industries: ['Tech', 'Manufacturing', 'Services'],
    languages: ['Arabic', 'French', 'English'],
    bio: 'Specializing in Algerian commercial law, compliance, and international business contracts for companies entering the Algerian market.',
    hourlyRate: 100,
    currency: 'USD',
    availability: 'Available This Week',
    category: 'Legal',
    isVerified: true,
    isOnline: true,
    responseTime: '< 3 hours',
    location: 'Algiers, Algeria',
  },
  {
    id: 'e4',
    name: 'Mehdi Tlemcani',
    avatar: 'https://i.pravatar.cc/150?img=7',
    title: 'Digital Marketing Expert',
    company: 'Founder @ DZDigital',
    rating: 4.6,
    reviewCount: 58,
    consultations: 185,
    yearsExperience: 7,
    expertise: ['SEO/SEM', 'Social Media', 'Brand Strategy', 'Content'],
    industries: ['E-commerce', 'FMCG', 'Tech'],
    languages: ['Arabic', 'French', 'English'],
    bio: 'Digital marketing expert with deep knowledge of the Algerian and North African digital landscape, consumer behavior and e-commerce.',
    hourlyRate: 80,
    currency: 'USD',
    availability: 'Available Today',
    category: 'Marketing',
    isVerified: false,
    isOnline: true,
    responseTime: '< 1 hour',
    location: 'Constantine, Algeria',
  },
  {
    id: 'e5',
    name: 'Farid Bensalem',
    avatar: 'https://i.pravatar.cc/150?img=9',
    title: 'CTO & Tech Advisor',
    company: 'ex-Google',
    rating: 4.9,
    reviewCount: 112,
    consultations: 440,
    yearsExperience: 14,
    expertise: ['Architecture', 'Cloud', 'AI/ML', 'Fintech'],
    industries: ['Technology', 'Banking', 'Telecom'],
    languages: ['Arabic', 'French', 'English'],
    bio: 'Former Google engineer now helping Algerian startups and enterprises with technology strategy, architecture and digital transformation.',
    hourlyRate: 200,
    currency: 'USD',
    availability: 'Available This Week',
    category: 'Technology',
    isVerified: true,
    isOnline: false,
    responseTime: '< 4 hours',
    location: 'Remote / Algiers',
  },
  {
    id: 'e6',
    name: 'Nadia Bouhired',
    avatar: 'https://i.pravatar.cc/150?img=10',
    title: 'HR & Talent Expert',
    company: 'HR Partners DZ',
    rating: 4.5,
    reviewCount: 43,
    consultations: 140,
    yearsExperience: 9,
    expertise: ['Talent Acquisition', 'HR Policy', 'Training', 'Org Design'],
    industries: ['All Industries'],
    languages: ['Arabic', 'French'],
    bio: 'HR specialist helping Algerian companies build strong teams, develop talent acquisition strategies and create effective HR frameworks.',
    hourlyRate: 90,
    currency: 'USD',
    availability: 'Available Tomorrow',
    category: 'HR',
    isVerified: true,
    isOnline: true,
    responseTime: '< 2 hours',
    location: 'Annaba, Algeria',
  },
];

export const MOCK_CONSULTATIONS: Consultation[] = [
  {
    id: 'c1',
    expertId: 'e1',
    expert: MOCK_EXPERTS[0],
    clientId: 'u1',
    date: '2026-05-28',
    time: '10:00 AM',
    duration: 60,
    type: 'video',
    status: 'upcoming',
    topic: 'Market Entry Strategy for North Africa',
    price: 150,
    currency: 'USD',
  },
  {
    id: 'c2',
    expertId: 'e2',
    expert: MOCK_EXPERTS[1],
    clientId: 'u1',
    date: '2026-05-30',
    time: '2:00 PM',
    duration: 90,
    type: 'video',
    status: 'upcoming',
    topic: 'Investment Portfolio Review',
    price: 180,
    currency: 'USD',
  },
  {
    id: 'c3',
    expertId: 'e1',
    expert: MOCK_EXPERTS[0],
    clientId: 'u1',
    date: '2026-05-10',
    time: '11:00 AM',
    duration: 60,
    type: 'video',
    status: 'completed',
    topic: 'Business Plan Review',
    price: 150,
    currency: 'USD',
  },
  {
    id: 'c4',
    expertId: 'e3',
    expert: MOCK_EXPERTS[2],
    clientId: 'u1',
    date: '2026-05-05',
    time: '3:00 PM',
    duration: 45,
    type: 'audio',
    status: 'completed',
    topic: 'Contract Review & Legal Advice',
    price: 75,
    currency: 'USD',
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'm1',
    senderId: 'e1',
    receiverId: 'u1',
    content: "Hello Karim! I've reviewed the documents you sent. Your market analysis is thorough, but I have some suggestions for the pricing strategy.",
    timestamp: '2026-05-26T09:15:00Z',
    type: 'text',
    isRead: true,
  },
  {
    id: 'm2',
    senderId: 'u1',
    receiverId: 'e1',
    content: "Thank you Sarah! That would be very helpful. Should we discuss the North African pricing vs. European pricing model?",
    timestamp: '2026-05-26T09:20:00Z',
    type: 'text',
    isRead: true,
  },
  {
    id: 'm3',
    senderId: 'e1',
    receiverId: 'u1',
    content: "Exactly. I have data showing that the optimal price point for your SaaS product in Algeria should be between 20-35% of your European pricing. Local purchasing power and competitive landscape are key factors.",
    timestamp: '2026-05-26T09:25:00Z',
    type: 'text',
    isRead: true,
  },
  {
    id: 'm4',
    senderId: 'u1',
    receiverId: 'e1',
    content: "That makes sense. Can you send me the detailed analysis? And shall we book a call to go through the full strategy?",
    timestamp: '2026-05-26T09:30:00Z',
    type: 'text',
    isRead: false,
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv1',
    expertId: 'e1',
    expert: MOCK_EXPERTS[0],
    lastMessage: MOCK_MESSAGES[3],
    unreadCount: 1,
    updatedAt: '2026-05-26T09:30:00Z',
  },
  {
    id: 'conv2',
    expertId: 'e2',
    expert: MOCK_EXPERTS[1],
    lastMessage: {
      id: 'm5',
      senderId: 'e2',
      receiverId: 'u1',
      content: 'Looking forward to our session on Friday!',
      timestamp: '2026-05-25T14:00:00Z',
      type: 'text',
      isRead: true,
    },
    unreadCount: 0,
    updatedAt: '2026-05-25T14:00:00Z',
  },
];

export const MOCK_REPORTS: Report[] = [
  {
    id: 'r1',
    title: 'Algeria Economic Outlook 2026',
    description: 'Comprehensive analysis of Algerian macroeconomic trends, investment climate, and sector opportunities for the coming year.',
    category: 'Economy',
    author: 'DA Research Team',
    publishedAt: '2026-05-01',
    readTime: 15,
    tags: ['Economy', 'Investment', 'Algeria'],
    isPremium: false,
  },
  {
    id: 'r2',
    title: 'Tech Startup Ecosystem Report: North Africa 2026',
    description: 'Deep dive into the booming tech startup ecosystem across Algeria, Morocco, and Tunisia.',
    category: 'Technology',
    author: 'Sarah Mansouri',
    publishedAt: '2026-04-15',
    readTime: 20,
    tags: ['Startups', 'Technology', 'North Africa'],
    isPremium: true,
  },
  {
    id: 'r3',
    title: 'Algerian Consumer Behavior Insights',
    description: 'Survey-based analysis of changing consumer preferences, digital adoption rates, and spending patterns in Algeria.',
    category: 'Marketing',
    author: 'Mehdi Tlemcani',
    publishedAt: '2026-03-20',
    readTime: 12,
    tags: ['Consumers', 'Marketing', 'Retail'],
    isPremium: false,
  },
  {
    id: 'r4',
    title: 'Legal Framework for Foreign Investment in Algeria',
    description: 'Updated guide on the regulatory environment, investment laws, and compliance requirements for foreign companies in Algeria.',
    category: 'Legal',
    author: 'Amina Khelil',
    publishedAt: '2026-04-01',
    readTime: 18,
    tags: ['Legal', 'Compliance', 'FDI'],
    isPremium: true,
  },
  {
    id: 'r5',
    title: 'Fintech Opportunities in Algeria 2026',
    description: 'Analysis of the rapidly growing fintech sector in Algeria, including mobile banking, payments, and digital lending.',
    category: 'Finance',
    author: 'Youssef Rahmani',
    publishedAt: '2026-05-10',
    readTime: 14,
    tags: ['Fintech', 'Banking', 'Digital'],
    isPremium: true,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rv1',
    authorId: 'u1',
    authorName: 'Karim Benali',
    rating: 5,
    content: "Sarah provided incredible insights about the Algerian market. Her knowledge of local business culture and regulatory environment is unmatched. Highly recommend!",
    date: '2026-05-10',
    expertId: 'e1',
    consultationId: 'c3',
  },
  {
    id: 'rv2',
    authorId: 'u2',
    authorName: 'Leila Brahimi',
    rating: 5,
    content: "Best strategic consultation I've had. Sarah helped us completely rethink our go-to-market strategy and the results have been outstanding.",
    date: '2026-04-22',
    expertId: 'e1',
    consultationId: 'c5',
  },
  {
    id: 'rv3',
    authorId: 'u3',
    authorName: 'Ahmed Ziani',
    rating: 4,
    content: "Very knowledgeable and professional. The strategy framework she provided has been a game changer for our expansion plans.",
    date: '2026-04-10',
    expertId: 'e1',
    consultationId: 'c6',
  },
];

export const MOCK_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'sp1',
    name: 'Starter',
    price: 49,
    currency: 'USD',
    period: 'monthly',
    features: [
      '3 Consultations / month',
      'Access to 50+ experts',
      'Basic market reports',
      'Chat messaging',
      'Email support',
    ],
    isPopular: false,
  },
  {
    id: 'sp2',
    name: 'Professional',
    price: 149,
    currency: 'USD',
    period: 'monthly',
    features: [
      '10 Consultations / month',
      'Access to ALL experts',
      'Full report library',
      'Priority scheduling',
      'Video & audio calls',
      'Dedicated account manager',
    ],
    isPopular: true,
  },
  {
    id: 'sp3',
    name: 'Enterprise',
    price: 449,
    currency: 'USD',
    period: 'monthly',
    features: [
      'Unlimited consultations',
      'Custom expert matching',
      'Exclusive research reports',
      'Team accounts (up to 10)',
      'API access',
      '24/7 priority support',
    ],
    isPopular: false,
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalConsultations: 12,
  hoursConsulted: 18,
  reportsRead: 24,
  expertsConnected: 8,
  progressPercent: 68,
  weeklyGoal: '2 consultations this week',
};

export const TIME_SLOTS = [
  { id: 't1', time: '9:00 AM', isAvailable: true },
  { id: 't2', time: '10:00 AM', isAvailable: false },
  { id: 't3', time: '11:00 AM', isAvailable: true },
  { id: 't4', time: '12:00 PM', isAvailable: true },
  { id: 't5', time: '1:00 PM', isAvailable: false },
  { id: 't6', time: '2:00 PM', isAvailable: true },
  { id: 't7', time: '3:00 PM', isAvailable: true },
  { id: 't8', time: '4:00 PM', isAvailable: false },
  { id: 't9', time: '5:00 PM', isAvailable: true },
];
