import React, { useEffect, useRef, useState, useCallback } from "react";
import {
  View,
  Text,
  StyleSheet,
  Pressable,
  SafeAreaView,
  Platform,
  Alert,
  ActivityIndicator,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useAppTheme } from "../../hooks/useAppTheme";
import { Fonts } from "../../theme";
import { useAppStore } from "../../store/useAppStore";
import { getSocket, callUser, acceptCall, rejectCall } from "../../services/socket";
import {
  startCall,
  answerCall,
  endCall,
  setMuted,
  setVideoEnabled,
  isWebRTCAvailable,
  CallType,
} from "../../services/webrtc";

// RTCView is not available — react-native-webrtc is not bundled.
// When WebRTC support is added via LiveKit, this will render live streams.
function getRTCView(): any {
  return null;
}

const CONTROL_SIZE = 56;

type CallStatus =
  | "idle"          // No active call
  | "outgoing"      // We dialed, waiting for answer
  | "incoming"      // Receiving a call
  | "connecting"    // Accepted, setting up WebRTC
  | "connected"     // Media streams flowing
  | "ended";        // Call finished

interface Props {
  onBack: () => void;
  peerName?: string;
  /** ID of the remote user to call (optional – if omitted the screen shows as callee UI) */
  peerUserId?: string;
  /** 'audio' | 'video' — defaults to video */
  callType?: CallType;
  /** Room / call ID – generated by the caller, forwarded to callee via socket */
  roomId?: string;
}

export const MeetingScreen: React.FC<Props> = ({
  onBack,
  peerName = "Participant",
  peerUserId,
  callType: initialCallType = "video",
  roomId: initialRoomId,
}) => {
  const { colors } = useAppTheme();

  // ── Expo Go guard ─────────────────────────────────────────────────────────
  if (!isWebRTCAvailable()) {
    return (
      <View style={[styles.root, { backgroundColor: "#1a1a1a", alignItems: "center", justifyContent: "center", padding: 32 }]}>
        <Ionicons name="videocam-off-outline" size={64} color="rgba(255,255,255,0.4)" />
        <Text style={[styles.headerTitle, { textAlign: "center", marginTop: 20, fontSize: 20 }]}>
          Live calls unavailable in Expo Go
        </Text>
        <Text style={{ color: "rgba(255,255,255,0.5)", textAlign: "center", marginTop: 12, fontSize: 14, lineHeight: 22 }}>
          Real-time voice & video requires a custom dev build.{"\n"}Run{" "}
          <Text style={{ color: "#22C55E", fontWeight: "700" }}>eas build --profile development</Text>
          {" "}to enable WebRTC calls.
        </Text>
        <Pressable
          style={[styles.controlBtn, { marginTop: 32, backgroundColor: "rgba(255,255,255,0.15)", width: 120, borderRadius: 12, height: 48 }]}
          onPress={onBack}
        >
          <Text style={{ color: "#fff", fontWeight: "700" }}>Go Back</Text>
        </Pressable>
      </View>
    );
  }
  const user = useAppStore((s) => s.user);

  const [status, setStatus] = useState<CallStatus>(peerUserId ? "outgoing" : "idle");
  const [callType, setCallType] = useState<CallType>(initialCallType);
  const [timer, setTimer] = useState("00:00");
  const [muted, setMutedState] = useState(false);
  const [videoOn, setVideoOn] = useState(initialCallType === "video");

  // Incoming call data (filled when we receive incoming_call)
  const incomingRef = useRef<{ callerId: string; callType: CallType; roomId: string } | null>(null);

  // WebRTC stream refs (RTCView expects URL strings from getObjectURL / objectURL)
  const [localStreamURL, setLocalStreamURL] = useState<string | null>(null);
  const [remoteStreamURL, setRemoteStreamURL] = useState<string | null>(null);

  const roomIdRef = useRef<string>(initialRoomId ?? `room_${Date.now()}`);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // ── Timer ────────────────────────────────────────────────────────────────

  const startTimer = useCallback(() => {
    let sec = 0;
    timerRef.current = setInterval(() => {
      sec += 1;
      const m = Math.floor(sec / 60);
      const s = sec % 60;
      setTimer(`${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`);
    }, 1000);
  }, []);

  const stopTimer = useCallback(() => {
    if (timerRef.current) clearInterval(timerRef.current);
  }, []);

  // ── Remote stream handler ─────────────────────────────────────────────────

  const handleRemoteStream = useCallback((stream: any) => {
    setRemoteStreamURL(stream.toURL ? stream.toURL() : null);
    setStatus("connected");
    startTimer();
  }, [startTimer]);

  // ── Socket listener for incoming / signaling events ────────────────────────

  useEffect(() => {
    const sock = getSocket();
    if (!sock) return;

    const onIncoming = (data: { callerId: string; callType: CallType; roomId: string }) => {
      incomingRef.current = data;
      setCallType(data.callType);
      setStatus("incoming");
    };

    const onAccepted = async (data: { accepterId: string; roomId: string }) => {
      if (data.roomId !== roomIdRef.current) return;
      setStatus("connecting");
      try {
        const stream = await startCall(
          data.accepterId,
          roomIdRef.current,
          callType,
          handleRemoteStream,
          handleCallEnded,
        );
        setLocalStreamURL(stream.toURL ? stream.toURL() : null);
      } catch (err: any) {
        Alert.alert("Call error", err?.message ?? "Could not start call.");
        handleCallEnded();
      }
    };

    const onRejected = () => {
      Alert.alert("Call declined", `${peerName} declined the call.`);
      handleCallEnded();
    };

    const onEnded = (data: { byUserId: string; roomId: string }) => {
      if (data.roomId !== roomIdRef.current) return;
      handleCallEnded();
    };

    sock.on("incoming_call", onIncoming);
    sock.on("call_accepted", onAccepted);
    sock.on("call_rejected", onRejected);
    sock.on("call_ended", onEnded);

    return () => {
      sock.off("incoming_call", onIncoming);
      sock.off("call_accepted", onAccepted);
      sock.off("call_rejected", onRejected);
      sock.off("call_ended", onEnded);
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [callType]);

  // ── Initiate outgoing call ────────────────────────────────────────────────

  useEffect(() => {
    if (status === "outgoing" && peerUserId) {
      callUser(peerUserId, initialCallType, roomIdRef.current);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ── Accept incoming call ───────────────────────────────────────────────────

  const handleAccept = useCallback(async () => {
    const inc = incomingRef.current;
    if (!inc) return;
    setStatus("connecting");
    acceptCall(inc.callerId, inc.roomId);
    roomIdRef.current = inc.roomId;

    try {
      // The offer arrives via socket; answerCall will be triggered from signaling
      // We start local media and wait for the offer via webrtc_offer socket event.
      // The webrtc.ts listener handles the offer → answer exchange automatically.
      const stream = await answerCall(
        inc.callerId,
        inc.roomId,
        inc.callType,
        {} as any, // offer will arrive via socket — webrtc service handles it
        handleRemoteStream,
        handleCallEnded,
      );
      setLocalStreamURL(stream.toURL ? stream.toURL() : null);
    } catch (err: any) {
      Alert.alert("Call error", err?.message ?? "Could not answer call.");
      handleCallEnded();
    }
  }, [handleRemoteStream]);

  // ── Reject incoming call ──────────────────────────────────────────────────

  const handleReject = useCallback(() => {
    const inc = incomingRef.current;
    if (inc) rejectCall(inc.callerId, inc.roomId);
    handleCallEnded();
  }, []);

  // ── End / hang up ─────────────────────────────────────────────────────────

  const handleCallEnded = useCallback(() => {
    stopTimer();
    setStatus("ended");
    setLocalStreamURL(null);
    setRemoteStreamURL(null);
    setTimeout(onBack, 800);
  }, [onBack, stopTimer]);

  const handleHangUp = useCallback(() => {
    if (peerUserId) {
      endCall(peerUserId, roomIdRef.current);
    } else if (incomingRef.current) {
      endCall(incomingRef.current.callerId, roomIdRef.current);
    }
    handleCallEnded();
  }, [peerUserId, handleCallEnded]);

  // ── Controls ──────────────────────────────────────────────────────────────

  const toggleMute = () => {
    const next = !muted;
    setMutedState(next);
    setMuted(next);
  };

  const toggleVideo = () => {
    const next = !videoOn;
    setVideoOn(next);
    setVideoEnabled(next);
  };

  // ─── Render helpers ───────────────────────────────────────────────────────

  const renderRemoteVideo = () => {
    const RTCView = getRTCView();
    if (remoteStreamURL && RTCView) {
      return (
        <RTCView
          streamURL={remoteStreamURL}
          style={styles.fullVideo}
          objectFit="cover"
          mirror={false}
        />
      );
    }
    return (
      <View style={styles.remotePlaceholder}>
        <View style={styles.avatarLarge}>
          <Ionicons name="person" size={64} color="rgba(255,255,255,0.5)" />
        </View>
        {status === "connecting" ? (
          <>
            <ActivityIndicator color="#fff" size="small" style={{ marginBottom: 8 }} />
            <Text style={styles.remoteLabel}>Connecting…</Text>
          </>
        ) : (
          <Text style={styles.remoteLabel}>
            {status === "outgoing" ? `Calling ${peerName}…` : `Waiting for ${peerName}…`}
          </Text>
        )}
      </View>
    );
  };

  const renderLocalPip = () => {
    if (!videoOn) return null;
    const RTCView = getRTCView();
    if (localStreamURL && RTCView) {
      return (
        <RTCView
          streamURL={localStreamURL}
          style={[styles.localPip, { borderColor: colors.tint }]}
          objectFit="cover"
          mirror
        />
      );
    }
    return (
      <View style={[styles.localPip, { borderColor: colors.tint, backgroundColor: "#333", alignItems: "center", justifyContent: "center" }]}>
        <Ionicons name="person" size={32} color="rgba(255,255,255,0.5)" />
      </View>
    );
  };

  // ─── Incoming call screen ─────────────────────────────────────────────────

  if (status === "incoming") {
    return (
      <View style={[styles.root, { backgroundColor: "#1a1a1a" }]}>
        <SafeAreaView style={[styles.safe, styles.incomingContainer]}>
          <Text style={styles.incomingTitle}>Incoming {callType} call</Text>
          <View style={styles.avatarLargeIncoming}>
            <Ionicons name="person" size={72} color="rgba(255,255,255,0.7)" />
          </View>
          <Text style={styles.incomingName}>{peerName}</Text>
          <View style={styles.incomingActions}>
            <Pressable style={[styles.controlBtn, styles.hangUpBtn]} onPress={handleReject}>
              <Ionicons name="call" size={28} color="#fff" style={{ transform: [{ rotate: "135deg" }] }} />
            </Pressable>
            <Pressable style={[styles.controlBtn, { backgroundColor: "#22C55E" }]} onPress={handleAccept}>
              <Ionicons name="call" size={28} color="#fff" />
            </Pressable>
          </View>
        </SafeAreaView>
      </View>
    );
  }

  // ─── Main call screen ─────────────────────────────────────────────────────

  return (
    <View style={[styles.root, { backgroundColor: "#1a1a1a" }]}>
      <SafeAreaView style={styles.safe}>
        {/* Header */}
        <View style={styles.header}>
          <Pressable
            onPress={handleHangUp}
            style={[styles.iconBtn, { backgroundColor: "rgba(255,255,255,0.15)" }]}
          >
            <Ionicons name="chevron-down" size={24} color="#fff" />
          </Pressable>
          <Text style={styles.headerTitle}>{peerName}</Text>
          <Text style={styles.timerText}>{timer}</Text>
        </View>

        {/* Remote video */}
        <View style={styles.remoteVideoContainer}>
          {renderRemoteVideo()}
        </View>

        {/* Local PiP */}
        {renderLocalPip()}

        {/* E2EE indicator */}
        <View style={styles.e2eeBadge}>
          <Ionicons name="lock-closed" size={11} color="#22C55E" />
          <Text style={styles.e2eeText}>End-to-end encrypted</Text>
        </View>

        {/* Controls */}
        <View style={styles.controls}>
          <Pressable
            style={[styles.controlBtn, { backgroundColor: muted ? "#EF4444" : "rgba(255,255,255,0.2)" }]}
            onPress={toggleMute}
          >
            <Ionicons name={muted ? "mic-off" : "mic"} size={26} color="#fff" />
          </Pressable>
          <Pressable
            style={[styles.controlBtn, { backgroundColor: !videoOn ? "#EF4444" : "rgba(255,255,255,0.2)" }]}
            onPress={toggleVideo}
          >
            <Ionicons name={videoOn ? "videocam" : "videocam-off"} size={26} color="#fff" />
          </Pressable>
          <Pressable style={[styles.controlBtn, { backgroundColor: "rgba(255,255,255,0.2)" }]}>
            <Ionicons name="camera-reverse" size={26} color="#fff" />
          </Pressable>
          <Pressable style={[styles.controlBtn, styles.hangUpBtn]} onPress={handleHangUp}>
            <Ionicons name="call" size={26} color="#fff" />
          </Pressable>
        </View>
      </SafeAreaView>
    </View>
  );
};

const styles = StyleSheet.create({
  root: { flex: 1 },
  safe: { flex: 1, justifyContent: "space-between", paddingTop: Platform.OS === "android" ? 24 : 0 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  iconBtn: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" },
  headerTitle: { flex: 1, fontSize: 18, fontWeight: "700", color: "#fff", fontFamily: Fonts.sans },
  timerText: { fontSize: 15, color: "rgba(255,255,255,0.8)", fontVariant: ["tabular-nums"] },

  remoteVideoContainer: { flex: 1, marginHorizontal: 12, borderRadius: 16, overflow: "hidden", backgroundColor: "#0d0d0d" },
  fullVideo: { flex: 1 },
  remotePlaceholder: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 },
  avatarLarge: { width: 100, height: 100, borderRadius: 50, backgroundColor: "rgba(255,255,255,0.1)", alignItems: "center", justifyContent: "center", marginBottom: 16 },
  remoteLabel: { fontSize: 17, fontWeight: "600", color: "rgba(255,255,255,0.9)", textAlign: "center" },

  localPip: {
    position: "absolute",
    top: 80,
    right: 24,
    width: 100,
    height: 140,
    borderRadius: 12,
    borderWidth: 2,
    overflow: "hidden",
    backgroundColor: "#2d2d2d",
  },

  e2eeBadge: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingBottom: 6,
  },
  e2eeText: { fontSize: 11, color: "#22C55E", fontWeight: "600" },

  controls: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 20,
    paddingVertical: 20,
    paddingBottom: 36,
  },
  controlBtn: {
    width: CONTROL_SIZE,
    height: CONTROL_SIZE,
    borderRadius: CONTROL_SIZE / 2,
    alignItems: "center",
    justifyContent: "center",
  },
  hangUpBtn: { backgroundColor: "#EF4444" },

  // Incoming call screen
  incomingContainer: { alignItems: "center", justifyContent: "center", gap: 20 },
  incomingTitle: { fontSize: 16, color: "rgba(255,255,255,0.7)", fontWeight: "600" },
  avatarLargeIncoming: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  incomingName: { fontSize: 26, color: "#fff", fontWeight: "800", fontFamily: Fonts.sans },
  incomingActions: { flexDirection: "row", gap: 40, marginTop: 16 },
});
